# Generated by Django 3.2.5 on 2021-07-17 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', pyuploadcare.dj.models.ImageField(blank=True, default=None)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('A', 'Одяг'), ('B', 'Взуття'), ('C', 'Аксесуари'), ('D', 'Інше')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', pyuploadcare.dj.models.ImageField(blank=True, default=None)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cust_app.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
