# Generated by Django 3.2.5 on 2021-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_app', '0002_auto_20210717_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products'),
        ),
    ]
