# Generated by Django 3.2.5 on 2021-07-17 19:41

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='logo',
            field=pyuploadcare.dj.models.ImageField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
