# Generated by Django 3.2.5 on 2021-07-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_app', '0005_auto_20210717_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
