# Generated by Django 3.2.5 on 2021-07-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_app', '0006_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
